variable "cidr_block" {}
variable "cluster_name" {}
variable "sg_cluster_name" {}
variable "sg_worker_name" {}
variable "subnet1_cidr" {}
variable "subnet2_cidr" {}
variable "subnet3_cidr" {}
variable "az1" {}
variable "az2" {}
variable "az3" {}
variable "subnet_name1" {}
variable "subnet_name2" {}
variable "subnet_name3" {}
variable "rt_name" {}
variable "cluster_role_name" {}
variable "worker_role_name" {}
variable "launch_template_name" {}
variable "instance_type" {}
variable "base_on_demand" {}
variable "percentage_on_demand" {}
variable "key_name" {}
variable "worker_desired_capacity" {}
variable "worker_min_size" {}
variable "worker_max_size" {}
variable "instance_type_asg1" {}
variable "instance_type_asg2" {}
variable "instance_type_asg3" {}
variable "volume_size" {}